//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dining_Room.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyWeek
    {
        public int ID { get; set; }
        public int SupplyID { get; set; }
        public int WeekID { get; set; }
        public System.DateTime YesterdayDate { get; set; }
    
        public virtual Supply Supply { get; set; }
        public virtual WeekCategory WeekCategory { get; set; }
    }
}
