//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dining_Room.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesterdayMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YesterdayMenu()
        {
            this.MenuWeek = new HashSet<MenuWeek>();
        }
    
        public int ID { get; set; }
        public int DishID { get; set; }
        public int CookID { get; set; }
        public double TotalSum { get; set; }
        public System.DateTime YesterdayDate { get; set; }
        public int Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuWeek> MenuWeek { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
